### ISSUE TITLE
calculate_groundtruth_heatmap

### ISSUE THREAD

**Issue by OriginalV** [VXallset/deep-high-resolution-net.TensorFlow#10]
in calculate_groundtruth_heatmap() function:

            # if the keypoint class is 3, continue
            if kepoint_class[b, n] == 3:
                continue

what's the meaning of these two lines?

**Comment by VXallset** [comment]
> in calculate_groundtruth_heatmap() function:
> 
> ```
>         # if the keypoint class is 3, continue
>         if kepoint_class[b, n] == 3:
>             continue
> ```
> 
> what's the meaning of these two lines?

@OriginalV 
For AI Challenger, the class of a keypoint is 3 indicates that the coordinate of this keypoint is not given (its x and y coordinates are both 0). For example, if keypoint_class[1, 2] =3, it means for the 3rd keypoint in the 2nd image, its coordinate is not given (therefore you can't see this keypoint in the image. Imagine the scene that there is a person in an image and you can only see its upper body. In this situation, you can't see the keypoint of its leg) Therefore, when generating the ground truth heat map,the value should be all 0, instead of a 0-matrix which has a small region whose value is 2-D Gaussian.

**Comment by henbucuoshanghai** [comment]
nice  ansers。   i  download the data,and found it ,3 is not given      tks
very kind of you

**Comment by OriginalV** [comment]
Good answer and thank you very much for your reply !!!
